server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: provider_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001   #匹配后提供服务的路由地址
          predicates:
            - Path=/provider/**   #断言,路径相匹配的进行路由
            # 此处注意，必须给provider8001工程加上server.servlet.context-path=/provider

        - id: consumer_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:80 #匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/**   #断言,路径相匹配的进行路由
            # 此处注意，必须给provider8001工程加上server.servlet.context-path=/provider


eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka